CREATE TABLE petition(
  id INT UNSIGNED AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  byWho VARCHAR(255) NOT NULL,
  target VARCHAR(255) NOT NULL,
  currentSupporters INT NOT NULL,
  goalSupporters INT NOT NULL,
  date VARCHAR(255) NOT NULL,
  overview TEXT NOT NULL,
  image VARCHAR(255),
  category VARCHAR(255),
  user_id INT NOT NULL,
  path VARCHAR(255),
  featured INT DEFAULT 1,
  victory INT DEFAULT 0,
  closed INT DEFAULT 0,
  letter TEXT,
  lastUpdate DATE,
  PRIMARY KEY (id)
);
